<?php

require_once 'GenerativeHelper.php';
require_once FLEXIONS_MODULES_DIR . '/Languages/FlexionsSwiftLang.php';


class GenerativeHelperForSwift extends GenerativeHelper {

    static function getCurrentClassNameWithPrefix($d, $classesPrefix = "") {
        if (!$d) return '$d should be set in getCurrentClassFragment( )';
        if (property_exists($d, 'name')) {
            return $classesPrefix . $d->name;
        } else {
            return 'UNDEFINDED-CLASS-FRAGMENT';
        }
    }

    static function defaultHeader(Flexed $f, $d) {
        $swiftHeader = "//
//  $f->fileName
//  $f->projectName
//
// THIS FILE AS BEEN GENERATED BY BARTLEBYFLEXIONS for $f->author
// DO NOT MODIFY THIS FILE YOUR MODIFICATIONS WOULD BE ERASED ON NEXT GENERATION!
//
// Copyright (c) 2016  $f->company  All rights reserved.
//";
        return $swiftHeader;

    }


    static function getBaseClass( $d) {
        /* @var $d EntityRepresentation */

        if (isset($d) && isset($d->instanceOf)) {
            return $d->instanceOf;
        } else {
            // Default base  for bartleby
            return GenerativeHelperForSwift::defaultBaseClass($d);
        }
    }

    static function defaultBaseClass($d) {
        /* @var $d EntityRepresentation */
        return 'ManagedModel';
    }


    static function isAGeneratedSubClass($d) {
        /* @var $d EntityRepresentation */
        return (isset($d) && isset($d->instanceOf));
    }

}

?>