<?php 

// /////////////////////////////////////////
// #1 Save the hypotypose to files
// /////////////////////////////////////////


hypotyposeToFiles();


// /////////////////////////////////////////
// #2 generate a consolidated header file 
// /////////////////////////////////////////

/* @var $outPutFolderRelativePath string */

if(file_exists(realpath($destination))==false){
	throw new Exception("Unexisting destination ".realpath($destination));
}

$generated='';
$h=Hypotypose::Instance();


// Let's write the list of the files we have created in the loop "Project"
$list = $h->flexedList [DefaultLoops::ENTITIES];
$list = array_merge($list,$h->flexedList [DefaultLoops::ACTIONS]);
$list = array_merge($list,$h->flexedList [DefaultLoops::PROJECT]);
$counter = 0;

foreach ( $list as $flexed ) {
    /* @var $flexed Flexed */
	if ($flexed->exclude === false) {
		// Let's add a human readable log.
		$counter ++;
        $line='';
		if (VERBOSE_FLEXIONS)
			fLog ( $counter . " " . $flexed->fileName. cr() , false );
		// Let's list the file name
		$line .= $counter.'# We have created "'.$flexed->package.''.$flexed->fileName . '"' . "\n";
		$generated .= $line;
	}
}

// We use the models variables
$f=new Flexed();
// This include sets $f properties
include FLEXIONS_SOURCE_DIR . "SharedMPS.php";
$f->package="";
$f->fileName="ReadMe.txt";

// We save the generated headers.
$filePath= $destination .$f->package. $f->fileName;
$c='Those files are generated by flexions do not modify them directly.'.cr();
$c.=$generated;
file_put_contents ( $filePath, $c );