<?php
/**
 * Created by PhpStorm.
 * User: bpds
 * Date: 11/07/15
 * Time: 08:53
 */

class GeneralUtils{

    /**
     * Returns the comment "header"
     *
     * @param Flexed $flexed
     * @return string
     */
    static function getCommentHeader($flexed) {
$r="//  ".$flexed->fileName."
//  ".$flexed->projectName."
//
//  Generated by Flexions do not modify
//  Copyright (c) ".  $flexed->year." ". $flexed->company." All rights reserved.\n \n";
        return $r;
    }


}
?>