<?php

require_once 'GenerativeHelper.php';
require_once FLEXIONS_MODULES_DIR . 'Languages/FlexionsSwiftLang.php';


class GenerativeHelperForSwift extends  GenerativeHelper{
    static function getCurrentClassNameWithPrefix($d, $classesPrefix = "") {
        if (!$d) return '$d should be set in getCurrentClassFragment( )';
        if (property_exists($d, 'name')) {
            return $classesPrefix . $d->name;
        } else {
            return 'UNDEFINDED-CLASS-FRAGMENT';
        }
    }

    static function defaultHeader(Flexed $f, $d) {
        $swiftHeader = "//
//  $f->fileName
//  $f->projectName
//
//  Generated by Flexions for $f->author on ?
//  https://github.com/benoit-pereira-da-silva/Flexions
//
";
        $willBePreserved=GenerativeHelper::flexedWillBePreserved($f);
        if ($willBePreserved==false){
            // We distinguish files that are generated once from "re-generable files"
            $swiftHeader.= "// DO NOT MODIFY THIS FILE YOUR MODIFICATIONS WOULD BE ERASED ON NEXT GENERATION!
// IF NECESSARY YOU CAN MARK THIS FILE TO BE PRESERVED
// IN THE PREPROCESSOR BY ADDING IN Hypotypose::instance().preservePath
//
";
        }

        $swiftHeader.="// Copyright (c) 2015  $f->company  All rights reserved.
//";
        return $swiftHeader;

    }
}

?>